name: Linux C++ Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cd MiniScript-cpp
          make
      - uses: actions/upload-artifact@v3  
        with:
          name: miniscript-linux
          path: MiniScript-cpp/miniscript
          if-no-files-found: error